### ISSUE TITLE
Missing directory 'tf_ggx_render_configs_1x1' under /auxiliary/tf_ggx_render_newparam/

### ISSUE THREAD

**Issue by qinneo-fu** [cocoakang/thinking-lightstage#1]
In tame_tamer.py, line 45:
`standard_rendering_parameters["config_dir"] = "auxiliary/tf_ggx_render_newparam/tf_ggx_render_configs_1x1/"`

But there doesn't exist this directoy under /auxiliary/tf_ggx_render_newparam/

Is it caused by a code typo or missing resource files?

**Comment by cocoakang** [comment]
Thanks for your issue. The missing files have been added.@qinneo-fu
